### ISSUE TITLE
Ansible Playbook fails on os-hardening role

### ISSUE THREAD

**Issue by davidogbonnah** [UKHomeOffice/development_environment#21]
Error message reads:

TASK [os-hardening : activate gpg-check for yum-repos]
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has not attribure 'stdout_lines'"}

**Comment by pixie79** [comment]
Please try the latest develop branch where this has been fixed

**Comment by dogbonnahNB** [comment]
Still receiving the same error:

dadmin@dadmin-workstation:~/GIT/development_environment/ansible$ git checkout
Your branch is up-to-date with 'origin/develop'.

TASK [os-hardening : activate gpg-check for yum-repos] *************************
task path: /opt/GIT/development_environment/roles/os-hardening/tasks/yum.yml:19
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "'dict object' has no attribute 'stdout_lines'"
}
	to retry, use: --limit @/opt/GIT/development_environment/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=42   changed=0    unreachable=0    failed=1

**Comment by pixie79** [comment]
This is an external role which is included, before you rerun you need to
ensure you have force updated the external roles.

Regards

Mark

**Comment by davidogbonnah** [comment]
Finally got it working. Cheers.
